# Generated by Django 4.1.3 on 2024-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
