# Generated by Django 4.1.3 on 2024-02-19 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Project_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=32, unique=True)),
                ('project', models.ManyToManyField(to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ManyToManyField(to='api.organization'),
        ),
        migrations.CreateModel(
            name='Organization_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=32, unique=True)),
                ('organization', models.ManyToManyField(to='api.organization')),
            ],
        ),
    ]
