# Generated by Django 4.1.3 on 2024-02-19 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_organization_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
